name: CI devops 2023

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    env:
      working-directory: ./simple-api-student
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3  # You can change the version as needed
        with:
          java-version: 17  # Change this to the desired JDK version

      - name: Build and test with Maven
        run: |
          mvn clean install  # Replace with your Maven build command
